#!/bin/bash

dune exec mickey --profile release < $1 > ${1%.*}.asm &&
CompArch/masm/masm -o < prelude.asm > prelude.obj &&
echo "heap:" >> ${1%.*}.asm
CompArch/masm/masm -o < ${1%.*}.asm > ${1%.*}.obj &&
CompArch/HW6/linker prelude.obj ${1%.*}.obj > ${1%.*}.exe &&
CompArch/mic1/mic1 CompArch/mic1/prom.dat ${1%.*}.exe