#!/bin/bash

dune exec mickey $1 ${1%.*}.asm &&
dune exec assembler prelude.asm prelude.obj &&
dune exec assembler ${1%.*}.asm ${1%.*}.obj &&
dune exec assembler heap.asm heap.obj &&
dune exec linker prelude.obj ${1%.*}.obj heap.obj ${1%.*}.exe &&
dune exec simulator ${1%.*}.exe